# Generated by Django 5.0.6 on 2025-03-01 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_province_user_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='academic_knowledge',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='available_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_genre',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='level_of_expertise',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='own_song',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_instrument',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
