# Generated by Django 5.0.6 on 2025-03-01 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_academic_knowledge_user_available_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_clothing',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
