# Generated by Django 5.0.6 on 2025-03-04 04:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_preferred_clothing'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='matched_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
