# Generated by Django 5.0.6 on 2025-03-04 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_matched_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='zipcode',
        ),
    ]
