# Generated by Django 5.0.6 on 2025-03-05 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_user_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='available_time',
            field=models.TextField(blank=True, null=True),
        ),
    ]
