# Generated by Django 5.0.6 on 2025-03-19 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_apple_music_user_instagram_user_is_premium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_distance',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
