# Generated by Django 5.0.6 on 2025-02-13 21:48

from django.db import migrations


def populate_static_data(apps, schema_editor):
    Question = apps.get_model('instrument_suggestion', 'Question')
    Instrument = apps.get_model('instrument_suggestion', 'Instrument')
    QuestionOption = apps.get_model('instrument_suggestion', 'QuestionOption')

    # Add static questions
    questions = [
        {"text": "Do you smoke?", "label": "Smoke"},
        {"text": "Do you work out?", "label": "Work Out"},
        {"text": "What type of sound do you find most appealing?", "label": "Preferred Sound"},
        {"text": "What type of feeling are you looking for while playing the instrument?", "label": "Playing Purpose"},
        {"text": "Based on your potential practice environment, is noise a concern for you?",
         "label": "Private Area Playability"},
        {"text": "Would you prefer to play in public or alone?", "label": "Public or Alone"},
        {"text": "Do you have any physical issues?", "label": "Physical Issues"},
        {"text": "In your opinion, how important is portability in choosing an instrument?", "label": "Portability"},
        {"text": "How much time and money would you be able to spend on your instrument's maintenance?",
         "label": "Maintenance Effort"},
        {"text": "How many years of experience do you have in music?", "label": "Experience (Years)"},
        {"text": "How would you rate your current musical skills?", "label": "Skill Level"},
        {"text": "Would you mind learning a difficult musical instrument?", "label": "Difficulty Level"},
        {"text": "What genres of music do you enjoy listening to the most?", "label": "Genres"},
    ]

    question_options = [
        {"label": "Smoke", "text": "Yes", "value": 0},
        {"label": "Smoke", "text": "Sometime", "value": 1},
        {"label": "Smoke", "text": "No", "value": 2},
        {"label": "Work Out", "text": "Yes", "value": 0},
        {"label": "Work Out", "text": "Sometime", "value": 1},
        {"label": "Work Out", "text": "No", "value": 2},
        {"label": "Preferred Sound", "text": "Mellow and soothing", "value": 0},
        {"label": "Preferred Sound", "text": "Bright and cheerful", "value": 1},
        {"label": "Preferred Sound", "text": "Deep and resonant", "value": 2},
        {"label": "Preferred Sound", "text": "Sharp and crisp", "value": 3},
        {"label": "Playing Purpose", "text": "Relaxation", "value": 0},
        {"label": "Playing Purpose", "text": "Energy Fulfillment", "value": 1},
        {"label": "Playing Purpose", "text": "Creativity", "value": 2},
        {"label": "Playing Purpose", "text": "Achievement", "value": 3},
        {"label": "Playing Purpose", "text": "Focus", "value": 4},
        {"label": "Private Area Playability", "text": "Yes, I need a very quiet instrument.", "value": 0},
        {"label": "Private Area Playability", "text": "Somewhat, but it doesn’t have to be silent", "value": 1},
        {"label": "Private Area Playability", "text": "No, noise is not a concern for me.", "value": 2},
        {"label": "Public or Alone", "text": "I prefer to play in public", "value": 0},
        {"label": "Public or Alone", "text": "I prefer to play alone", "value": 1},
        {"label": "Public or Alone", "text": "No difference.", "value": 2},
        {"label": "Physical Issues", "text": "No Issues", "value": 0},
        {"label": "Physical Issues", "text": "Sore hands or fingers", "value": 1},
        {"label": "Physical Issues", "text": "Back or neck pain", "value": 2},
        {"label": "Physical Issues", "text": "Tired arms", "value": 3},
        {"label": "Physical Issues", "text": "Hearing problems", "value": 4},
        {"label": "Portability", "text": "Very important", "value": 0},
        {"label": "Portability", "text": "Somewhat important", "value": 1},
        {"label": "Portability", "text": "Not important", "value": 2},
        {"label": "Maintenance Effort", "text": "Minimal", "value": 0},
        {"label": "Maintenance Effort", "text": "Moderate", "value": 1},
        {"label": "Maintenance Effort", "text": "Significant", "value": 2},
        {"label": "Maintenance Effort", "text": "I haven’t thought about this", "value": 3},
        {"label": "Experience (Years)", "text": "0", "value": 0},
        {"label": "Experience (Years)", "text": "1 – 3", "value": 1},
        {"label": "Experience (Years)", "text": "4 – 6", "value": 2},
        {"label": "Experience (Years)", "text": "7 – 10", "value": 3},
        {"label": "Experience (Years)", "text": "11 – 15", "value": 4},
        {"label": "Experience (Years)", "text": "16 - 20", "value": 5},
        {"label": "Skill Level", "text": "Beginner", "value": 0},
        {"label": "Skill Level", "text": "Intermediate", "value": 1},
        {"label": "Skill Level", "text": "Advanced", "value": 2},
        {"label": "Difficulty Level", "text": "I prefer an easy-to-learn musical instrument", "value": 0},
        {"label": "Difficulty Level", "text": "I don't mind if it's moderately challenging to learn", "value": 1},
        {"label": "Difficulty Level", "text": "I'm fine with learning a difficult instrument", "value": 2},
        {"label": "Genres", "text": "Classical", "value": 0},
        {"label": "Genres", "text": "Jazz / Blues", "value": 1},
        {"label": "Genres", "text": "Rock", "value": 2},
        {"label": "Genres", "text": "Folk / Traditional", "value": 3},
        {"label": "Genres", "text": "Country", "value": 4},
        {"label": "Genres", "text": "Latin", "value": 5},
        {"label": "Genres", "text": "Pop", "value": 6},
    ]

    for question in questions:
        created_question, _ = Question.objects.get_or_create(text=question["text"], label=question["label"])
        # Add static questions options
        filtered_options = [option for option in question_options if option["label"] == created_question.label]
        for option in filtered_options:
            QuestionOption.objects.get_or_create(question=created_question, text=option["text"], value=option["value"])

    # Add static instruments
    instruments = [
        {"name": "Piano"},
        {"name": "Violin"},
        {"name": "Acoustic Guitar"},
        {"name": "Electric Guitar"},
        {"name": "Drums and Percussion"},
        {"name": "Flute"},
        {"name": "Saxophone"},
    ]
    for instrument in instruments:
        Instrument.objects.get_or_create(name=instrument["name"])


class Migration(migrations.Migration):
    dependencies = [
        ('instrument_suggestion', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_static_data),
    ]
