# Generated by Django 5.0.6 on 2025-03-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrument_suggestion', '0002_populate_static_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.CharField(default='Instrument', max_length=20),
            preserve_default=False,
        ),
    ]
