# Generated by Django 5.0.6 on 2025-03-01 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instrument_suggestion', '0003_question_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='section',
        ),
    ]
